/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package br.com.leoleal.connectionreporter;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

@SuppressWarnings("unused")
@Kroll.module(name="ConnectionreporterAndroid", id="br.com.leoleal.connectionreporter")
public class ConnectionreporterAndroidModule extends KrollModule
{

	// Standard Debugging variables
	private static final String TAG = "ConnectionreporterAndroidModule";
    private static final boolean DBG = TiConfig.LOGD;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public ConnectionreporterAndroidModule()
	{
		super();
	}
 
    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app)
    {
        //Log.d(LCAT, "inside onAppCreate");
        // put module init code that needs to run when the application is created
    }
 
    // Methods
    @Kroll.method
    public String getConnectionType()
    {
        return ConnectionManager.getConnectionType();
    }

}