/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package br.com.leoleal.connectionreporter;
import android.net.ConnectivityManager;
import android.telephony.TelephonyManager;

import org.appcelerator.titanium.TiApplication;
@SuppressWarnings("static-access")
public class ConnectionManager {
    public static String getConnectionType() {
        TiApplication appContext = TiApplication.getInstance();
		ConnectivityManager manager = (ConnectivityManager)appContext.getSystemService(appContext.CONNECTIVITY_SERVICE);
        android.net.NetworkInfo mobile = manager.getNetworkInfo(ConnectivityManager.TYPE_MOBILE);
 
        if(mobile.isAvailable()) {
            return getMobileConnectionType();
        }
        else
        {
            return "None";
        }   
    }
 
    private static String getMobileConnectionType() {  
        TiApplication appContext = TiApplication.getInstance();
		TelephonyManager telManager = (TelephonyManager)appContext.getSystemService(appContext.TELEPHONY_SERVICE);
        switch (telManager.getNetworkType()) {
                case 1: return "GPRS";
                case 2: return "EDGE";
                case 3: return "UMTS";
                case 4: return "CDMA";
                case 5: return "EVDO";
                case 6: return "EVDO";
                case 8: return "HSDPA";
                case 9: return "HSUPA";
                case 10: return "HSPA";
                case 12: return "EVDO";
                case 13: return "LTE";
                case 15: return "HSPA+";
                default: return "Unknown Mobile";
        }
    }
}